export const data: {
  [key: string]: {
    [key: number]: {
      [courses: string]: {
        [key: string]: string;
      }[];
    };
  };
} = {
  semester1: {
    100: {
      resources: [
        {
          name: "GES 100",
          code: "GES100.1",
          title: "GES 100.1 Computer Skill in English",
          lecture_notes: "https://drive.google.com/drive/folders/1MKJ1eL_5J7PMbEbqpjhauUNurm-oeTKd",
          materials: "https://drive.google.com/drive/folders/1mCv9Sty_HnPPmsJkJRUWD1lpn4hk8b66",
          past_questions: "https://drive.google.com/drive/folders/1ZUjS0-Mlv-qwFbA3xuZv-e2AuWu6tQ8G",
        },
        {
          name: "GES 102",
          code: "GES102.1",
          title: "GES 102.1 Introduction to Logic & Philosophy",
          lecture_notes: "https://drive.google.com/drive/folders/1g8LYKJU4ZiCqJ2PeA7RenDPlHiLwx1He",
          materials: "https://drive.google.com/drive/folders/1mzmBUitesSFKOYDTkbEjTFevaD44LFsv",
          past_questions: "https://drive.google.com/drive/folders/19SAfZmLIBHMwSRMYGL8BlQqv1S5zqr2z",
        },
        {
          name: "MTH 110",
          code: "MTH110.1",
          title: "MTH 110.1 Algebra and Trigonometry",
          lecture_notes: "https://drive.google.com/drive/folders/1KrETBHYXPxqn-0T1twKvisOpxs5guXMA",
          materials: "https://drive.google.com/drive/folders/1RGvlg2T5CF33eIKY1s2cWIFZlQlHJJkc",
          past_questions: "https://drive.google.com/drive/folders/1h2EQROhbM7OpQ3WiP6PnW4DR2ssykJoN",
        },
        {
          name: "MTH 120",
          code: "MTH120.1",
          title: "MTH 120.1 Calculus",
          lecture_notes: "https://drive.google.com/drive/folders/1f4a1q6aaI-2SnFgTSpYe08ZvKxhSmqsJ",
          materials: "https://drive.google.com/drive/folders/1rZdE6bd0BH8d_wQkbUVPJgHA0jsQZYVk",
          past_questions: "https://drive.google.com/drive/folders/17NH5GWvpn1BbTPyq9o0PkXxp_PvGAGHv",
        },
        {
          name: "PHY 101",
          code: "PHY101.1",
          title: "PHY 101.1 Mechanics and Properties of Matter",
          lecture_notes: "https://drive.google.com/drive/folders/12b9hz87pbxEZ4p-VDXNTj6ao9gxe6Uqs",
          materials: "https://drive.google.com/drive/folders/1yAGvhwC97G9-2hKle-BqUEywmLIpnTXt",
          past_questions: "https://drive.google.com/drive/folders/1gRndl6oyHgP1mhGt5IerjVeYMYJBnKxJ",
        },
        {
          name: "CSC 180",
          code: "CSC180.1",
          title: "CSC 180.1 Introduction to Computer Science and Basic Programming",
          lecture_notes: "https://drive.google.com/drive/folders/1YfVj2_1zNNqwFRt636sfAViEGzRUAFO6",
          materials: "https://drive.google.com/drive/folders/1-q6A34ZiBOBUmUpFDd0IwIHHEcs6ZWvJ",
          past_questions: "https://drive.google.com/drive/folders/1scQvs1yGwB3eG9pGco9SLHhv4armilQu",
        },
        {
          name: "CHM 130",
          code: "CHM130.1",
          title: "CHM 130.1 General Chemistry",
          lecture_notes: "https://drive.google.com/drive/folders/1IVMe9oB8erD5umAUlaZXed8_CsemaFEE",
          materials: "https://drive.google.com/drive/folders/1nBfkjZ_OFiMWy219-bRer8tDbB3_kkSf",
          past_questions: "https://drive.google.com/drive/folders/1XRNJoCGavn6i5E4wJW_vC-Kslv_7dNag",
        },
        {
          name: "FSB 101",
          code: "FSB101.1",
          title: "FSB 101.1 General Biology 1",
          lecture_notes: "https://drive.google.com/drive/folders/1O6xFwH4qK39U_XYpFRRL7TMCPjh_mpUS",
          materials: "https://drive.google.com/drive/folders/1KPyIT0vlBdL6TVZ5gdrAewRtXqihhxNv",
          past_questions: "https://drive.google.com/drive/folders/1w2TKJYxpsSde7v2GjByPCCRs1apW7dl5",
        },
      ],
    },
    200: {    resources: [
        {
          name: "MTH 270",
          code: "MTH270.1",
          title: "Numerical Analysis",
          lecture_notes: "https://drive.google.com/drive/folders/1e1dbT6inQSvMO9Alj5eV80kj3wYWkzZ1",
          materials: "https://drive.google.com/drive/folders/1083e_I3QJ3fRVD9vSVR192z8td9gT8yx",
          past_questions: "https://drive.google.com/drive/folders/1dUOgu1WPSbnH3m5Ps5nBWEFJnclUy6gO",
        },
        {
          name: "STA 260",
          code: "STA260.1",
          title: "Introduction To Probability and statistics",
          lecture_notes: "https://drive.google.com/drive/folders/1N5gNwWgt1MpCHeWcgKZBTR4Z7-r0OmI",
          materials: "https://drive.google.com/drive/folders/1ehWii-NRr70HPKCKulMRUGGnr6Mape1Y",
          past_questions: "https://drive.google.com/drive/folders/1-CzBpGCfTgve3oyjdOFIxC66SwRcQ-Ta",
        },
        {
          name: "CSC 280",
          code: "CSC280.1",
          title: "Introduction To Computer Programming (Fortran)",
          lecture_notes: "https://drive.google.com/drive/folders/1lg-ZvItIOMcTGWRFImBW29dUPdnsMi4F",
          materials: "https://drive.google.com/drive/folders/1Dx1GVjXdzsOt5cTdhB2HAbzTgdvrKT4A",
          past_questions: "https://drive.google.com/drive/folders/1Ielk_Q0G4955LzogvNtkN97zKMW5wTmM",
        },
        {
          name: "CSC 281",
          code: "CSC281.1",
          title: "Computer System Fundamentals",
          lecture_notes: "https://drive.google.com/drive/folders/13u5gKsUc8E-WViQn1BxvKcinBoVGVQNW",
          materials: "https://drive.google.com/drive/folders/1DyqyzM8wbkh5vK2pJWHjtlBlhNq-bPEB",
          past_questions: "https://drive.google.com/drive/folders/1bJ6_8GEf-Nfg0vW5nOiPOMKQIkmL9nIi",
        },
        {
          name: "CSC 283",
          code: "CSC283.1",
          title: "Introduction To Information Systems and File Structures",
          lecture_notes: "https://drive.google.com/drive/folders/1MK88SJedA5yGRh9b-T5ia897iA-p_TvV",
          materials: "https://drive.google.com/drive/folders/1dZh0X8K5tibXEy1_JVbET_wYhX41JlVI",
          past_questions: "https://drive.google.com/drive/folders/1ujOhnXn40d4I6rvOCazg6t3Y6ihDSQJr",
        },
        {
          name: "CSC 284",
          code: "CSC284.1",
          title: "CSC 284.1 ",
          lecture_notes: "https://drive.google.com/drive/folders/15igKIvm9NElYfV26t_qgA4tCjt6iikEd",
          materials: "https://drive.google.com/drive/folders/1SNfVN1rNZdDy0sa2w5wWbJ554kRnk_a6",
          past_questions: "https://drive.google.com/drive/folders/1Mq3Po83oUhMLBSu-Jac-UooesRiemiX6",
        },
        {
          name: "CSC 288",
          code: "CSC288.1",
          title: "Structured Programming",
          lecture_notes: "https://drive.google.com/drive/folders/1bGyi4I0cQqTicWr1dNo9bR6das6CChbX",
          materials: "https://drive.google.com/drive/folders/1vvxM45Mt79JhD9LauXqVNq_3zGFHFiAu",
          past_questions: "https://drive.google.com/drive/folders/1FY4qq8Yi2eY3ftiB6H4N5tfiGapDL9zL",
        },
        {
          name: "MTH 210",
          code: "MTH210.1",
          title: "Linear Algebra",
          lecture_notes: "https://drive.google.com/drive/folders/1WbfvwHnI7Grf3LhojSyx4f57tEFnzhPh",
          materials: "https://drive.google.com/drive/folders/1ci2dVSplFYYJUspXwYgp1hzQ09-qCM74",
          past_questions: "https://drive.google.com/drive/folders/1UJp8w8oCjm93rrkb_A9pzraMy0E5i1gU",
        },
      ],},
    300: {    resources: [
        {
          name: "CSC 382",
          code: "CSC382.1",
          title: "Computer Architecture I",
          lecture_notes: "https://drive.google.com/drive/folders/1DKphNyO6kMMaT_RH_Vox2k9NAqTf1P9c",
          materials: "https://drive.google.com/drive/folders/1kkEUExH11zYp5B9nxGYfIsnyo01WV4Kn",
          past_questions: "https://drive.google.com/drive/folders/1dwh4hC3dzngjP8nXDpeQNESTgzHAtcGQ",
        },
        {
          name: "CSC 394",
          code: "CSC394.1",
          title: "Operating Systems",
          lecture_notes: "https://drive.google.com/drive/folders/1K9lMf5WHoh3SpWYIyo8V96uRTtQTA_ta",
          materials: "https://drive.google.com/drive/folders/1zOHXJyHiXh1Uo5KN-cDnxcqzNhzsSe_x",
          past_questions: "https://drive.google.com/drive/folders/1CNZPFlPE8hbpo3THKcE9wk4uUYVk-Ce4",
        },
        {
          name: "CSC 395",
          code: "CSC395.1",
          title: "Introduction to software engineering",
          lecture_notes: "https://drive.google.com/drive/folders/171SCpGwaJ_udL6Hzuq5Lqrk_SamZn-ME",
          materials: "https://drive.google.com/drive/folders/1TtarYgXz-hD219cqNZtA6zSwAS12Q56G",
          past_questions: "https://drive.google.com/drive/folders/1Y23XVCyz8gGlJXgKOirl9zgdOsJH9eV9",
        },
        {
          name: "CSC 396",
          code: "CSC396.1",
          title: "Automata theory, Computability and Formal Language",
          lecture_notes: "https://drive.google.com/drive/folders/1wVpm-ZptU_WWAErJZL4KDqTvKwrlwMOW",
          materials: "https://drive.google.com/drive/folders/1U76D7htT1qACFS0D1FotpEaCKTpQY89b",
          past_questions: "https://drive.google.com/drive/folders/1FZDAuz8WwWvFfMlBTv4NSL-rPdYxdYuQ",
        },
        {
          name: "CSC 397",
          code: "CSC397.1",
          title: "Computational Method",
          lecture_notes: "https://drive.google.com/drive/folders/1hSdRteOy90c1DZLT3J7bvTOqvjRUwvmN",
          materials: "https://drive.google.com/drive/folders/1EYNhiYYLUAD0DE3frF1aJvYJb8WM3CzH",
          past_questions: "https://drive.google.com/drive/folders/1pIXp89ozA4sEyijdZvAt5A74uQJHD8K",
        },
        {
          name: "GES 300",
          code: "GES300.1",
          title: "Fundamentals of Enterpreneurship",
          lecture_notes: "https://drive.google.com/drive/folders/1F39f52FnKbvpNCei-iNU6vGLlAdEp2Zm",
          materials: "https://drive.google.com/drive/folders/1FY0vyqfnFP12RYKlkt0lMbno1RaCoKKp",
          past_questions: "https://drive.google.com/drive/folders/1yteT6NlkBFUiAxK8pjYvjhV3dmetyxJr",
        },
        {
          name: "STA 370",
          code: "STA370.1",
          title: "Operational Research",
          lecture_notes: "https://drive.google.com/drive/folders/1HJRmt_LHBscUNvP4O_c1TCO0U6Kx7bSK",
          materials: "https://drive.google.com/drive/folders/1LD0joHlxf9WlmN0eFzvMGtjN8xQQp1J3",
          past_questions: "https://drive.google.com/drive/folders/1yh11MV-Km1bVPEjqUg-qzKVfaK7l0UB9",
        },
    
      ],},
    400: {    resources: [
        {
          name: "GES 400",
          code: "GES400.1",
          title: "Enterpreneurship",
          lecture_notes: "",
          materials: "",
          past_questions: "",
        },
        {
          name: "CSC 480",
          code: "CSC 480.1",
          title: "Database Management",
          lecture_notes: "https://drive.google.com/drive/folders/1tQBEMX_1l8g6_clcEKogt4w728YmcrFk",
          materials: "https://drive.google.com/drive/folders/1CQmbc1R6X_imfsAgKHta6NNwg6Xw62VT",
          past_questions: "https://drive.google.com/drive/folders/1a1GLPIN5tJVvVrN6_jHYqgOCOWkIDsR6",
        },
        {
          name: "CSC 481",
          code: "CSC481.1",
          title: "Object Oriented Programming II(Java, Ruby, Python)",
          lecture_notes: "https://drive.google.com/drive/folders/1wInV0Y0-HNJS6yiQKksXAkcPu7Nl3Oq5",
          materials: "https://drive.google.com/drive/folders/15B1zp6UcQybq-kicYRGlq_WNw1Liq8uI",
          past_questions: "https://drive.google.com/drive/folders/1JSV2Clq-JabZQSm8ze0IlPLQgq6mIyUZ",
        },
        {
          name: "CSC 482",
          code: "CSC482.1",
          title: "Compiler Construction",
          lecture_notes: "https://drive.google.com/drive/folders/15cXDtifs8lFnhbE_7RYFBeDg9pOnU5rE",
          materials: "https://drive.google.com/drive/folders/1mfvfDxzolMFoAY6A5svi1imANCy5STAK",
          past_questions: "https://drive.google.com/drive/folders/1nJmfP_TpSmnINJmfPmqBGtLh5XXib4e8",
        },
        {
          name: "CSC 483",
          code: "CSC483.1",
          title: "Algorithms And COmplexity Analysis",
          lecture_notes: "https://drive.google.com/drive/folders/17NaBHte94dZrs0YRa-zLFM-BNd21YpJy",
          materials: "https://drive.google.com/drive/folders/1tWE1s2fTYhEfmvx2ySetMY0654xpGLcN",
          past_questions: "https://drive.google.com/drive/folders/1Dg5KX6VzQ4hPDKUvuEs_HGDgs4pYnjLw",
        },
        {
          name: "CSC 486",
          code: "CSC486.1",
          title: "System Analysis and Design",
          lecture_notes: "https://drive.google.com/drive/folders/1HOkRLqe2kjTthLp-YBvEATla6tTXUnsP",
          materials: "https://drive.google.com/drive/folders/1o3foMsRMMoTfKfC6OlQ8jjZU6bp8649Z",
          past_questions: "https://drive.google.com/drive/folders/1De_V4-lW8JpHwsjX1D5PivDDG0SG4JH1",
        },
        {
          name: "CSC 496",
          code: "CSC496.1",
          title:"Programming Languages (4th and 5th Generation)",
          lecture_notes: "https://drive.google.com/drive/folders/1eBjV43Kf3o-4EIM0HI93aB5aR6YKC8MN",
          materials: "https://drive.google.com/drive/folders/1u-wv649oblM58VpFh3V-pTU18cizGAw5",
          past_questions: "https://drive.google.com/drive/folders/1yADToDnxXMooyxZswNmhKDpSVU3zypmx",
        },
        {
          name: "CSC 498",
          code: "CSC498.1",
          title: "Computer Network & Data Communications",
          lecture_notes: "https://drive.google.com/drive/folders/1E6_ndaiCMMZEh0z4eA3I8i5lBwGTefHO",
          materials: "https://drive.google.com/drive/folders/1R0wPo8W_WdrqH7qnllL9xiBfW-1vclNG",
          past_questions: "https://drive.google.com/drive/folders/1R0wPo8W_WdrqH7qnllL9xiBfW-1vclNG",
        },
      ],},
  },
  semester2: {
    100: {    resources: [
        {
          name: "GES 101",
          code: "GES101.2",
          title: "Computer Appreciation and Application",
          lecture_notes: "https://drive.google.com/drive/folders/1Fh5Kj3aH7AWgNnbzy2fiG0n0mJI3nhwv",
          materials: "https://drive.google.com/drive/folders/16TcgL0zcYcsoeGbUufNz0c-VI_F2xJmo",
          past_questions: "https://drive.google.com/drive/folders/10nCvhmagEq2qC63TX0hwIoc3mUccrju1",
        },
        {
          name: "GES 103",
          code: "GES103.2",
          title: "Nigeria's people and culture",
          lecture_notes: "https://drive.google.com/drive/folders/1hA16MIIGXsEQhgsLwhl0pso1P5u2FAo",
          materials: "https://drive.google.com/drive/folders/1kU1dT4mRDnY8oenEILZgshhyjXY9aGGb",
          past_questions: "https://drive.google.com/drive/folders/1SesqrtK_Pg7p6TOUgT8YquDD4v9nZk9I",
        },
        {
          name: "MTH 114",
          code: "MTH114.2",
          title: "Introduction To Sets Logic And Algebra",
          lecture_notes: "https://drive.google.com/drive/folders/1chZceDapFX5xp__AN3yKz9Pde_8fZRsj",
          materials: "https://drive.google.com/drive/folders/1OJlnDKIt1A8ETZpSs80n03ZYYC9-dYad",
          past_questions: "https://drive.google.com/drive/folders/1iWxw1j5qIvk4ONpHEfrA5s07syer4ctP",
        },
        {
          name: "MTH 124",
          code: "MTH124.2",
          title: "Coordinate Geometry",
          lecture_notes: "https://drive.google.com/drive/folders/1_acmQCOqSjqXrFkIhQ5iTfHrwE2JJqG7",
          materials: "https://drive.google.com/drive/folders/1evMGkdwbPvs2TgBqvyVlTdy25qIdxlZR",
          past_questions: "https://drive.google.com/drive/folders/1VanyTiv1T6mSGUPdDz_EcWlnb-mOuNoT",
        },
        {
          name: "PHY 103",
          code: "PHY103.2",
          title: "Laboratory Practices II",
          lecture_notes: "https://drive.google.com/drive/folders/1_e6rZ1s0K6zgtGmr721h6blrhSNM0Z_v",
          materials: "https://drive.google.com/drive/folders/1A1ejjooPZmQ2-YeYr6xiHyf5a5tIBcAE",
          past_questions: "https://drive.google.com/drive/folders/1D83cE9FWXmbVaRYY9_bvlM9dEfdSOwaT",
        },
        {
          name: "PHY 112",
          code: "PHY112.2",
          title: "Introducing to Electricity and Magnetism",
          lecture_notes: "https://drive.google.com/drive/folders/1pnq4WwtXtLjeRT2D-iZCSJXd1-irlZhO",
          materials: "https://drive.google.com/drive/folders/1XQsZ7V-oVk4Aym1StMP0a22tjyBOj1cY",
          past_questions: "https://drive.google.com/drive/folders/1L2lB-NwRTDOgtMo_snGoe8lHzZni_bsm",
        },
        {
          name: "CSC 182",
          code: "CSC182.2",
          title: "Computer Applications",
          lecture_notes: "https://drive.google.com/drive/folders/1IpEeLEVq4fD6u27WjnhqnYYLROoQw0lW",
          materials: "https://drive.google.com/drive/folders/1-Sgjn2w16IgyzcMyydwSdhYgVVJEmHfJ",
          past_questions: "https://drive.google.com/drive/folders/1mpSUidOdE-JpJNDLRzauZFJfiHdzosTP",
        },
      
      ],},
    200: {    resources: [
        {
          name: "CSC 282",
          code: "CSC282.2",
          title: "Database Programming",
          lecture_notes: "https://drive.google.com/drive/folders/1IAyEuqYuEH_6Kbk1X98p1X_jyPsnUrY_",
          materials: "https://drive.google.com/drive/folders/1aHTv2qLdCyUtUCSVKv8UlpmkO-gIPyyg",
          past_questions: "https://drive.google.com/drive/folders/1eOU1Yl4dtp0QB--hwspUMmI52lJz-Z6R",
        },
        {
          name: "CSC 285",
          code: "CSC285.2",
          title: "Digital Dessigns And MicroProcessors",
          lecture_notes: "https://drive.google.com/drive/folders/1k30BgAuHJMhCFsw7m23WmgovMDTKJ3YW",
          materials: "https://drive.google.com/drive/folders/1L18Ph9djTgDMgLGl_ErdXK_s1_bRiXpM",
          past_questions: "https://drive.google.com/drive/folders/1rRS9NjQhCmUVBmjpXhWfFtcj2AADWhUn",
        },
        {
          name: "CSC 286",
          code: "CSC286.2",
          title: "Data Structures",
          lecture_notes: "https://drive.google.com/drive/folders/1ziTJbeSI966SMnNVb0vhSdn6o4UQyQ31",
          materials: "https://drive.google.com/drive/folders/19X2GCm4o5Do41-Lw5aWutgUkF62vF7SN",
          past_questions: "https://drive.google.com/drive/folders/1lJDgcY0ND3iEKZz-ekPz8pUFkO8AOfF4",
        },
        {
          name: "CSC 287",
          code: "CSC287.2",
          title: "Object Oriented Programming I(C++)",
          lecture_notes: "https://drive.google.com/drive/folders/1XHBJ5yioofb8fZXklvenF3N6Xr3X3RBK",
          materials: "https://drive.google.com/drive/folders/1NPy-c2Kn23dGsNFPdYXC7Zs_p-MKrPAL",
          past_questions: "https://drive.google.com/drive/folders/1-p-W696Cx8ttULJElspEoquIZr5wknZE",
        },
       
        {
          name: "MTH 224",
          code: "MTH224.2",
          title: "Mathematical Methods 1",
          lecture_notes: "https://drive.google.com/drive/folders/1Q-8hS8HC8TEpWIlLd0nOWzDqv5bou08z",
          materials: "https://drive.google.com/drive/folders/1icUg_B8rZrr1VLGNfhaTLPB1OJk35gm8",
          past_questions: "https://drive.google.com/drive/folders/1zGblfw_0DtjyxtuesTschD-m7v98Unm_",
        },
        {
          name: "MTH 250",
          code: "MTH250.2",
          title: "Elementary Differential Equations",
          lecture_notes: "https://drive.google.com/drive/folders/1k7dfzPM2jUhhYorXD4P7m_vItRDlmtHS",
          materials: "https://drive.google.com/drive/folders/1gSajrQxujzKu71jFURzOVw0zzTqxl6dQ",
          past_questions: "https://drive.google.com/drive/folders/1p0fKRom-TlXZn9blXS1THO32mivdpjaQ",
        },
        {
          name: "STA 262",
          code: "STA262.2",
          title: "Mathematical Statistics 1",
          lecture_notes: "https://drive.google.com/drive/folders/18ptlLKPMaeY8PpfCd5-OEeuXPMyb0GuP",
          materials: "https://drive.google.com/drive/folders/1G3f66pr-Zvsu1fIDwkIXDefNFOMRm6iq",
          past_questions: "https://drive.google.com/drive/folders/131S7SxB0FVpccuwJ04IdILF-UcEVONBo",
        },
      ],},
    300: {    resources: [
       {
        name:"CSC 300",
        code:"CSC300.2",
        title:"Industrial Training"
       }
      ],},
    400: {    resources: [
        {
          name: "CSC 491",
          code: "CSC491.2",
          title: "Computer Modeling and Simulation",
          lecture_notes: "https://drive.google.com/drive/folders/1rbg3gAz__cX7yrcJYxj5c-SLM0dWFJDD",
          materials: "https://drive.google.com/drive/folders/1MuiMFFTwVFZ00deUfPLCYSfLxR81L-AQ",
          past_questions: "https://drive.google.com/drive/folders/1PUBsmCdxP6b3DspdJZX_410Z1XBTorBX",
        },
        {
          name: "CSC 492",
          code: "CSC492.2",
          title: "Computer Graphics",
          lecture_notes: "https://drive.google.com/drive/folders/15vtxEbFtjSdKDAoufLm6O3OIp91cyw9Y",
          materials: "https://drive.google.com/drive/folders/1Jyb8isVNsBfAhIUS9Yx0Og1jfd4fg6om",
          past_questions: "https://drive.google.com/drive/folders/1chwr1HV3DtOhmfJoONyLsRfSZYJxDnoE",
        },
        {
          name: "CSC 493",
          code: "CSC493.2",
          title: "Internet and Web Applications",
          lecture_notes: "https://drive.google.com/drive/folders/1GLM2bTnxYiTL685jUCc-nov8sslE8B_X",
          materials: "https://drive.google.com/drive/folders/1rfDhAoMRIrZtU308n1yBXEQQ6ArX63V5",
          past_questions: "https://drive.google.com/drive/folders/1vx2gERVKytSQ_nO9efgr-xvO-ft30ev1",
        },
        {
          name: "CSC 494",
          code: "CSC494.2",
          title: "Introduction To Artificial Intelligence",
          lecture_notes: "https://drive.google.com/drive/folders/18-w6yLWCMU6a-TbpofWjG5y4Iq6kKA0W",
          materials: "https://drive.google.com/drive/folders/1JKvu85Uo_QPNQqIbj_3X2JWrQY_ukl9l",
          past_questions: "https://drive.google.com/drive/folders/1Lnry0b318HXTxc7I72htqUUFyPi7cMaJ",
        },
        {
          name: "CSC 495",
          code: "CSC495.2",
          title: "Computer Architecture II",
          lecture_notes: "https://drive.google.com/drive/folders/1Ox3ZDxpP-cMRbT-gtQv6u2XSw73gxDyZ",
          materials: "https://drive.google.com/drive/folders/1AN2h-8CFEQmvFysXTcP04a3aJ46T8dC5",
          past_questions: "https://drive.google.com/drive/folders/1DaaezbJwEroL0zKBxWf212M6x8WLx4iv",
        },
        {
          name: "CSC 497",
          code: "CSC497.2",
          title: "Project Management",
          lecture_notes: "https://drive.google.com/drive/folders/12HVq2Pg6j8_UmJsvdSf5yOK9JSqhdIaH",
          materials: "https://drive.google.com/drive/folders/1QFnSdHKE7yv1zgvxeyXNUC28RW38VSKQ",
          past_questions: "https://drive.google.com/drive/folders/1cquAWmuvlMYoYJ8Q7_6KgDaLRDq9ISod",
        },
       
      ],},
  },
};
